<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_product-item</name>
   <tag></tag>
   <elementGuidId>229c03d0-2273-47e5-b147-17fe480a2340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,&quot;noo-product-item&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
